; Added to the installer script generated by CPack.
; When the app updates itself it runs the installer with /SILENT: start the new version afterwards.
[Run]
Filename: "{app}\VideoCompressor.exe"; Flags: nowait; Check: WizardSilent
